import type { ColumnSchema, CustomColumnMessages } from '@ku-utils/custom-columns';

export const DEMO_CUSTOM_COLUMN_MESSAGES: CustomColumnMessages = {
  customColumns: '自定义列',
  searchPlaceholder: '搜索列名',
  selectAll: '全选',
  invertSelection: '反选',
  emptySearch: '未找到匹配列',
  selectedCount: (selected, max) => `已选择 ${selected}/${max} 列`,
  reset: '重置',
  fixedColumnsTip: '固定列不可取消',
  emptySelected: '请至少选择一列',
  configNamePlaceholder: '请输入配置名称',
  cancel: '取消',
  save: '保存',
  saveToLocal: '保存到本地',
  readFromLocal: '读取本地配置',
  complete: '完成',
  customConfig: '自定义配置',
  defaultConfigLabel: '默认配置',
  noNameLabel: '未命名配置',
  groupFallback: '未分组',
  operationColumnLabel: '操作',
  maxSelectedWarning: (max) => `最多选择 ${max} 列`,
  configNameRequired: '请输入配置名称',
  configNameExists: '配置名称已存在',
  configSaved: '配置已保存',
};

export const BASIC_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'score',
    label: '评分',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    sortable: true,
    renderType: 'float',
    renderArgs: [2, true],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'float',
    renderArgs: [2, false],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'rate',
    label: '转化率',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'percent',
    renderArgs: [1, true],
    group: '比率指标',
    isDefault: true,
  },
];

export const NESTED_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    label: '投放指标',
    align: 'center',
    children: [
      {
        prop: 'amount',
        label: '数量',
        minWidth: 100,
        align: 'right',
        renderType: 'integer',
        isDefault: true,
      },
      {
        prop: 'score',
        label: '评分',
        minWidth: 100,
        align: 'right',
        renderType: 'integer',
        isDefault: true,
      },
    ],
  },
  {
    label: '效果指标',
    align: 'center',
    children: [
      {
        prop: 'cost',
        label: '成本',
        minWidth: 110,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
      {
        prop: 'roi',
        label: 'ROI',
        minWidth: 100,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
      {
        prop: 'rate',
        label: '转化率',
        minWidth: 100,
        align: 'right',
        renderType: 'percent',
        isDefault: true,
      },
    ],
  },
];

/** schemaVersion 演示：相对 BASIC 删除 score、重命名 rate→cvtRate */
export const VERSION_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    renderType: 'float',
    renderArgs: [2, true],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    renderArgs: [2, false],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'cvtRate',
    label: '转化率(新)',
    minWidth: 110,
    align: 'right',
    renderType: 'percent',
    renderArgs: [1, true],
    group: '比率指标',
    isDefault: true,
  },
];

/** schema.fixed：弹窗内不可取消勾选 */
export const SCHEMA_FIXED_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量（固定）',
    minWidth: 110,
    align: 'right',
    renderType: 'integer',
    fixed: true,
    isDefault: true,
  },
  {
    prop: 'score',
    label: '评分',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
  {
    prop: 'rate',
    label: '转化率',
    minWidth: 100,
    align: 'right',
    renderType: 'percent',
    isDefault: true,
  },
];
