import {
  AppstoreOutline,
  ArrowRightOutline,
  CheckCircleOutline,
  CheckOutline,
  CloseOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExclamationCircleFill,
  FilterOutline,
  FundOutline,
  LoadingOutline,
  LockOutline,
  LogoutOutline,
  MenuOutline,
  MinusOutline,
  PlusOutline,
  ReloadOutline,
  SearchOutline,
  ShareAltOutline,
  StarFill,
  SunOutline,
  SyncOutline,
  TableOutline,
  UpOutline,
} from '@ant-design/icons-angular/icons';

/** 全局静态注册的图标（按需 import，禁止全量动态加载） */
export const ZORRO_ICONS = [
  AppstoreOutline,
  ArrowRightOutline,
  CheckCircleOutline,
  CheckOutline,
  CloseOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExclamationCircleFill,
  FilterOutline,
  FundOutline,
  LoadingOutline,
  LockOutline,
  LogoutOutline,
  MenuOutline,
  MinusOutline,
  PlusOutline,
  ReloadOutline,
  SearchOutline,
  ShareAltOutline,
  StarFill,
  SunOutline,
  SyncOutline,
  TableOutline,
  UpOutline,
];
