export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'release',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'eslint-config',
        'prettier-config',
        'tsconfig',
        'stylelint-config',
        'utils',
        'hooks',
        'directives',
        'ui',
        'ui-vue2',
        'design-tokens',
        'constants',
        'request',
        'i18n',
        'types',
        'nuxt-module',
        'custom-columns',
        'v2-custom-columns',
        'marketing',
        'report',
        'landing-report',
        'report-standalone',
        'landing-report-standalone',
        'pay',
        'cli',
        'create-app',
        'kv3-admin',
        'docs',
        'deps',
        'ci',
        'release',
      ],
    ],
    'subject-max-length': [2, 'always', 100],
  },
};
