import type { ColumnSchema } from '@ku-utils/v2-custom-columns';

export const BASIC_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'score',
    label: '评分',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    sortable: true,
    renderType: 'float',
    renderArgs: [2, true],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'float',
    renderArgs: [2, false],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'rate',
    label: '转化率',
    minWidth: 100,
    align: 'right',
    sortable: true,
    renderType: 'percent',
    renderArgs: [1, true],
    group: '比率指标',
    isDefault: true,
  },
];

export const NESTED_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    label: '投放指标',
    align: 'center',
    children: [
      {
        prop: 'amount',
        label: '数量',
        minWidth: 100,
        align: 'right',
        renderType: 'integer',
        isDefault: true,
      },
      {
        prop: 'score',
        label: '评分',
        minWidth: 100,
        align: 'right',
        renderType: 'integer',
        isDefault: true,
      },
    ],
  },
  {
    label: '效果指标',
    align: 'center',
    children: [
      {
        prop: 'cost',
        label: '成本',
        minWidth: 110,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
      {
        prop: 'roi',
        label: 'ROI',
        minWidth: 100,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
      {
        prop: 'rate',
        label: '转化率',
        minWidth: 100,
        align: 'right',
        renderType: 'percent',
        isDefault: true,
      },
    ],
  },
];

/** schemaVersion 演示：相对 BASIC 删除 score、重命名 rate→cvtRate */
export const VERSION_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    group: '数值指标',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    renderType: 'float',
    renderArgs: [2, true],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    renderArgs: [2, false],
    group: '金额指标',
    isDefault: true,
  },
  {
    prop: 'cvtRate',
    label: '转化率(新)',
    minWidth: 110,
    align: 'right',
    renderType: 'percent',
    renderArgs: [1, true],
    group: '比率指标',
    isDefault: true,
  },
];

/** schema.fixed：弹窗内不可取消勾选 */
export const SCHEMA_FIXED_COLUMN_SCHEMAS: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量（固定）',
    minWidth: 110,
    align: 'right',
    renderType: 'integer',
    fixed: true,
    isDefault: true,
  },
  {
    prop: 'score',
    label: '评分',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    isDefault: true,
  },
  {
    prop: 'cost',
    label: '成本',
    minWidth: 110,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
  {
    prop: 'rate',
    label: '转化率',
    minWidth: 100,
    align: 'right',
    renderType: 'percent',
    isDefault: true,
  },
];
