/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearancePicker: typeof import('./../components/AppearancePicker.vue')['default']
    BasePagination: typeof import('./../components/BasePagination.vue')['default']
    BrandLogoMark: typeof import('./../components/BrandLogoMark.vue')['default']
    CellApp: typeof import('./../components/CellApp.vue')['default']
    CellDateTime: typeof import('./../components/CellDateTime.vue')['default']
    CellNameId: typeof import('./../components/CellNameId.vue')['default']
    CellState: typeof import('./../components/CellState.vue')['default']
    DateRange: typeof import('./../components/DateRange.vue')['default']
    DialogPreviewVideo: typeof import('./../components/DialogPreviewVideo.vue')['default']
    DoFilterPanel: typeof import('./../components/DoFilterPanel.vue')['default']
    DoFormSection: typeof import('./../components/DoFormSection.vue')['default']
    DoNamePattern: typeof import('./../components/DoNamePattern.vue')['default']
    DoNumberSetter: typeof import('./../components/DoNumberSetter.vue')['default']
    DoSelector: typeof import('./../components/DoSelector.vue')['default']
    DoSorter: typeof import('./../components/DoSorter.vue')['default']
    DoTxtSetter: typeof import('./../components/DoTxtSetter.vue')['default']
    DoWordsTag: typeof import('./../components/DoWordsTag.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderProfileMenu: typeof import('./../components/HeaderProfileMenu.vue')['default']
    IconPlayOutline: typeof import('./../components/icons/IconPlayOutline.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTimeWeekPicker: typeof import('./../components/ScheduleTimeWeekPicker.vue')['default']
    TableWrap: typeof import('./../components/TableWrap.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
